### ISSUE TITLE
Explain relationship of this repo and Kit

### ISSUE THREAD

**Issue by Strajk** [johnlindquist/globals#1]
Heya 👋 I'm trying to understand Kit and found a link to this repo in this [comment](https://github.com/johnlindquist/kit/discussions/131#discussioncomment-1601709). Can you shed some light on what this repo does in Readme?

Thanks, for everything u do :)

**Comment by johnlindquist** [comment]
@Strajk This repo is meant to be node common libs not strictly specific to "Kit".

Like if you're writing a node script without any Kit prompts and just want to be lazy and use globals.

The other goals with this and https://github.com/johnlindquist/kit-internal had to do with creating both ESM and CJS bundles since the `kitapp` Electron project didn't support ESM-only bundles when I started (I had a working fork, but haven't made the time to integrate it all together).
